name: API Tests

on:
  push:
    branches: [ main, develop, dev, staging ]
  pull_request:
    branches: [ main, develop, dev, staging ]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  api-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      FORCE_REQUIRE_PAGINATION: 'true'
      NODE_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.18.3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run API tests
        run: pnpm run test:api -- --runInBand

      - name: Upload test results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-logs
          path: |
            junit.xml
            coverage
          if-no-files-found: ignore
