name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Typecheck (if you use tsc)
        run: npm run build:check || echo "no type-check script"

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Build client & server
        run: |
          npm run build || true
          # produce a no-bundle JS wrapper as a fallback
          npx esbuild server/index.ts --platform=node --format=esm --outfile=dist-server/index.nobundle.js

      - name: Detect app edits
        id: app-edits
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} > changed_files.txt || true
          echo "changed_files=$(cat changed_files.txt | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Conditional build/test (web)
        if: contains(steps.app-edits.outputs.changed_files, 'client/')
        run: npm run build

      - name: Conditional build/test (server)
        if: contains(steps.app-edits.outputs.changed_files, 'server/')
        run: npm run check:ts

