name: web-e2e
on: [push, pull_request]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies (web)
        working-directory: apps/web
        run: npm ci || npm install
      - name: Install Playwright browsers
        working-directory: apps/web
        run: npx playwright install --with-deps
      - name: Run E2E tests
        working-directory: apps/web
        env:
          VITE_API_BASE: http://localhost:5173
        run: npm run test:e2e
